-- 가입된 회원정보를 저장할 테이블
CREATE TABLE SCOTT.MYUSERS (
	NUM NUMBER(38,0) NOT NULL,
	NAME VARCHAR2(100) NOT NULL,
	ID VARCHAR2(100) NOT NULL,
	PWD VARCHAR2(100) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL,
	PROFILEIMAGE VARCHAR2(100) NULL,
	"ROLE" VARCHAR2(100) DEFAULT USER NULL,
	CREATEDAT DATE DEFAULT SYSDATE NOT NULL,
	CONSTRAINT MYUSERS_PK PRIMARY KEY (NUM)
);
COMMENT ON COLUMN SCOTT.MYUSERS."ROLE" IS 'role IN (''USER'', ''STAFF'', ''ADMIN'')';


